version: '3.1'

x-logging: &logging
  driver: 'json-file'
  options:
    max-size: '20m'
    max-file: '5'

services:
  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MARIADB_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MARIADB_DATABASE=$DB_WORDPRESS_DATABASE
      - MARIADB_USER=$DB_WORDPRESS_USER
      - MARIADB_PASSWORD=$DB_WORDPRESS_PASSWORD
    volumes:
      - ./.mariadb:/var/lib/mysql
    logging: *logging
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - network

  wordpress:
    depends_on:
      - mysql
    image: wordpress:5.8.2-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=$DB_WORDPRESS_DATABASE
      - WORDPRESS_DB_USER=$DB_WORDPRESS_USER
      - WORDPRESS_DB_PASSWORD=$DB_WORDPRESS_PASSWORD
    volumes:
      - ./php-conf/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./.wordpress:/var/www/html
    logging: *logging
    networks:
      - network

  nginx:
    depends_on:
      - wordpress
    image: nginx:1.21.4-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./.certbot:/etc/letsencrypt
      - ./.wordpress:/var/www/html
    logging: *logging
    networks:
      - network
    command: "/bin/sh -c 'while :; do sleep 24h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./.certbot:/etc/letsencrypt
      - ./.wordpress:/var/www/html
    logging: *logging
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  network:
    driver: bridge